### PR TITLE
Fix dependency handling

### LINKED ISSUE #151: Support Output in UnmarshalPropertyValue
When unmarshaling property values that are Outputs for #144, the provider [failed]( https://github.com/pulumi/pulumi-terraform-module/blob/35f15c3349809e8f1300d487d968b55ee614a5fa/pkg/property/unmarshal.go#L114) in Unmarshal with `contract.Failf("Output is not yet supported in UnmarshalPropertyValue")`.

As a result, we're currently not able to send the Output values in Construct.

### LINKED ISSUE #234: Dependency information lost for RDS module depending on AWS resources
I have the following Pulumi program:

```typescript
import * as pulumi from "@pulumi/pulumi";
import * as rds from "@pulumi/rds";
import * as aws from "@pulumi/aws"


//Make a VPC
const vpc = new aws.ec2.Vpc("myVpc", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
});

// Create a new security group within the VPC
const securityGroup = new aws.ec2.SecurityGroup("mySecurityGroup", {
    vpcId: vpc.id,
    description: "Allow MySQL access",
    ingress: [
        {
            protocol: "tcp",
            fromPort: 3306,
            toPort: 3306,
            cidrBlocks: ["0.0.0.0/0"],
        },
    ],
    egress: [
        {
            protocol: "-1",
            fromPort: 0,
            toPort: 0,
            cidrBlocks: ["0.0.0.0/0"],
        },
    ],
});

// Create a subnet for us-west-2a within the VPC
const subnet2a = new aws.ec2.Subnet("subnet2a", {
    vpcId: vpc.id,
    cidrBlock: "10.0.1.0/24",
    availabilityZone: "us-west-2a",
});

// Create a subnet for us-west-2b the VPC
const subnet2b = new aws.ec2.Subnet("subnet2b", {
    vpcId: vpc.id,
    cidrBlock: "10.0.2.0/24",
    availabilityZone: "us-west-2b",
})

const testrdsmodule = new rds.Module("test-rds", {
    identifier: "test-rds-module",
    engine: "mysql",
    instance_class: "db.t3.micro",
    allocated_storage: 20,
    db_name: "testrdsmoduledatabase",
    username: "pulumipus",
    password: "hawaii",
    skip_final_snapshot: true,
    deletion_protection: false,


    // DB parameter group
    family: "mysql8.0",

    // DB subnet group
    create_db_subnet_group: true,
    subnet_ids: [subnet2a.id, subnet2b.id],

    // DB option group
    major_engine_version: "8.0",
    vpc_security_group_ids: [securityGroup.id]

})
```

It successfully creates everything.

When running `pulumi destroy`, this fails because Pulumi tries to destroy the AWS resources first:

```
Previewing destroy (dev-check-no-changes)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/aws-rds-module/dev-check-no-changes/previews/8c28bf89-5e53-418b-b640-b7e8016a3a8a

     Type                                 Name                                                                      Plan       Info
 -   pulumi:pulumi:Stack                  aws-rds-module-dev-check-no-changes                                       delete     2 warnings
 -   ├─ aws:ec2:Subnet                    subnet2a                                                                  delete     
 -   ├─ aws:ec2:SecurityGroup             mySecurityGroup                                                           delete     
 -   ├─ aws:ec2:Subnet                    subnet2b                                                                  delete     
 -   ├─ aws:ec2:Vpc                       myVpc                                                                     delete     
 -   └─ rds:index:Module                  test-rds                                                                  delete     
 -      ├─ rds:tf:aws_db_subnet_group     module.test-rds.module.db_subnet_group.aws_db_subnet_group.this[0]        delete     
 -      ├─ rds:tf:aws_db_instance         module.test-rds.module.db_instance.aws_db_instance.this[0]                delete     
 -      ├─ rds:index:ModuleState          test-rds-state                                                            delete     
 -      ├─ rds:tf:aws_db_option_group     module.test-rds.module.db_option_group.aws_db_option_group.this[0]        delete     
 -      └─ rds:tf:aws_db_parameter_group  module.test-rds.module.db_parameter_group.aws_db_parameter_group.this[0]  delete     
```

And then fails:

```
Previewing destroy (dev-check-no-changes)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/aws-rds-module/dev-check-no-changes/previews/8c28bf89-5e53-418b-b640-b7e8016a3a8a

     Type                                 Name                                                                      Plan       Info
 -   pulumi:pulumi:Stack                  aws-rds-module-dev-check-no-changes                                       delete     2 warnings
 -   ├─ aws:ec2:Subnet                    subnet2a                                                                  delete     
 -   ├─ aws:ec2:SecurityGroup             mySecurityGroup                                                           delete     
 -   ├─ aws:ec2:Subnet                    subnet2b                                                                  delete     
 -   ├─ aws:ec2:Vpc                       myVpc                                                                     delete     
 -   └─ rds:index:Module                  test-rds                                                                  delete     
 -      ├─ rds:tf:aws_db_subnet_group     module.test-rds.module.db_subnet_group.aws_db_subnet_group.this[0]        delete     
 -      ├─ rds:tf:aws_db_instance         module.test-rds.module.db_instance.aws_db_instance.this[0]                delete     
 -      ├─ rds:index:ModuleState          test-rds-state                                                            delete     
 -      ├─ rds:tf:aws_db_option_group     module.test-rds.module.db_option_group.aws_db_option_group.this[0]        delete     
 -      └─ rds:tf:aws_db_parameter_group  module.test-rds.module.db_parameter_group.aws_db_parameter_group.this[0]  delete     

Diagnostics:
  pulumi:pulumi:Stack (aws-rds-module-dev-check-no-changes):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module

Resources:
    - 11 to delete

Do you want to perform this destroy? yes
Destroying (dev-check-no-changes)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/aws-rds-module/dev-check-no-changes/updates/20

     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     pulumi:pulumi:Stack       aws-rds-module-dev-check-no-changes  **failed**              1 error; 2 warnings
 -   ├─ aws:ec2:Subnet         subnet2a                             **deleting failed**     2 errors
 -   ├─ aws:ec2:SecurityGroup  mySecurityGroup                      **deleting failed**     1 error
 -   ├─ aws:ec2:Subnet         subnet2b                             deleted (0.74s)         
     └─ aws:ec2:SecurityGroup  mySecurityGrouperror:   sdk-v2/provider2.go:515: sdk.helper_schema: de
                      **failed**              1 error

Diagnostics:
  aws:ec2:Subnet (subnet2a):
    error:   sdk-v2/provider2.go:515: sdk.helper_schema: deleting ENIs for EC2 Subnet (subnet-0089d0ea5c56874e5): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 79120c18-784c-46d3-8f38-8ba320dca8cb, api error AuthFailure: You do not have permission to access the specified resource.
    
    : provider=aws@6.72.0
    error: deleting urn:pulumi:dev-check-no-changes::aws-rds-module::aws:ec2/subnet:Subnet::subnet2a: 1 error occurred:
    	* deleting ENIs for EC2 Subnet (subnet-0089d0ea5c56874e5): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 79120c18-784c-46d3-8f38-8ba320dca8cb, api error AuthFailure: You do not have permission to access the specified resource.

  aws:ec2:SecurityGroup (mySecurityGroup):
    error: deleting urn:pulumi:dev-check-no-changes::aws-rds-module::aws:ec2/securityGroup:SecurityGroup::mySecurityGroup: 1 error occurred:
    	* deleting ENIs using Security Group (sg-01b80436ca56f720f): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 84bbf0cd-b697-4890-860a-a4a573851674, api error AuthFailure: You do not have permission to access the specified resource.

  aws:ec2:SecurityGroup (mySecurityGroup
):
    error:   sdk-v2/provider2.go:515: sdk.helper_schema: deleting ENIs using Security Group (sg-01b80436ca56f720f): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 84bbf0cd-b697-4890-860a-a4a573851674, api error AuthFailure: You do not have permission to access the specified resource.
    
    : provider=aws@6.72.0

  pulumi:pulumi:Stack (aws-rds-module-dev-check-no-changes):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module
    error: update failed

Resources:
    - 1 deleted

Duration: 3s
```

Attempting the same program with setting `dependsOn` fails similarly. Pulumi still tries to delete the subnets first.

Updated program (same as above, save last line):

```
import * as pulumi from "@pulumi/pulumi";
import * as rds from "@pulumi/rds";
import * as aws from "@pulumi/aws"


//Make a VPC
const vpc = new aws.ec2.Vpc("myVpc", {
    cidrBlock: "10.0.0.0/16",
    enableDnsHostnames: true,
    enableDnsSupport: true,
});

// Create a new security group within the VPC
const securityGroup = new aws.ec2.SecurityGroup("mySecurityGroup", {
    vpcId: vpc.id,
    description: "Allow MySQL access",
    ingress: [
        {
            protocol: "tcp",
            fromPort: 3306,
            toPort: 3306,
            cidrBlocks: ["0.0.0.0/0"],
        },
    ],
    egress: [
        {
            protocol: "-1",
            fromPort: 0,
            toPort: 0,
            cidrBlocks: ["0.0.0.0/0"],
        },
    ],
});

// Create a subnet for us-west-2a within the VPC
const subnet2a = new aws.ec2.Subnet("subnet2a", {
    vpcId: vpc.id,
    cidrBlock: "10.0.1.0/24",
    availabilityZone: "us-west-2a",
});

// Create a subnet for us-west-2b the VPC
const subnet2b = new aws.ec2.Subnet("subnet2b", {
    vpcId: vpc.id,
    cidrBlock: "10.0.2.0/24",
    availabilityZone: "us-west-2b",
})

const testrdsmodule = new rds.Module("test-rds", {
    identifier: "test-rds-module",
    engine: "mysql",
    instance_class: "db.t3.micro",
    allocated_storage: 20,
    db_name: "testrdsmoduledatabase",
    username: "pulumipus",
    password: "hawaii",
    skip_final_snapshot: true,
    deletion_protection: false,


    // DB parameter group
    family: "mysql8.0",

    // DB subnet group
    create_db_subnet_group: true,
    subnet_ids: [subnet2a.id, subnet2b.id],

    // DB option group
    major_engine_version: "8.0",
    vpc_security_group_ids: [securityGroup.id]

}, {dependsOn: [subnet2a, subnet2b, vpc, securityGroup]})
```

Similar failure:
```
Destroying (dev-check-no-changes)

View in Browser (Ctrl+O): https://app.pulumi.com/guinevere-pulumi-corp/aws-rds-module/dev-check-no-changes/updates/20

     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     Type                      Name                                 Status                  Info
     pulumi:pulumi:Stack       aws-rds-module-dev-check-no-changes  **failed**              1 error; 2 warnings
 -   ├─ aws:ec2:Subnet         subnet2a                             **deleting failed**     2 errors
 -   ├─ aws:ec2:SecurityGroup  mySecurityGroup                      **deleting failed**     1 error
 -   ├─ aws:ec2:Subnet         subnet2b                             deleted (0.74s)         
     └─ aws:ec2:SecurityGroup  mySecurityGrouperror:   sdk-v2/provider2.go:515: sdk.helper_schema: de
                      **failed**              1 error

Diagnostics:
  aws:ec2:Subnet (subnet2a):
    error:   sdk-v2/provider2.go:515: sdk.helper_schema: deleting ENIs for EC2 Subnet (subnet-0089d0ea5c56874e5): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 79120c18-784c-46d3-8f38-8ba320dca8cb, api error AuthFailure: You do not have permission to access the specified resource.
    
    : provider=aws@6.72.0
    error: deleting urn:pulumi:dev-check-no-changes::aws-rds-module::aws:ec2/subnet:Subnet::subnet2a: 1 error occurred:
    	* deleting ENIs for EC2 Subnet (subnet-0089d0ea5c56874e5): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 79120c18-784c-46d3-8f38-8ba320dca8cb, api error AuthFailure: You do not have permission to access the specified resource.

  aws:ec2:SecurityGroup (mySecurityGroup):
    error: deleting urn:pulumi:dev-check-no-changes::aws-rds-module::aws:ec2/securityGroup:SecurityGroup::mySecurityGroup: 1 error occurred:
    	* deleting ENIs using Security Group (sg-01b80436ca56f720f): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 84bbf0cd-b697-4890-860a-a4a573851674, api error AuthFailure: You do not have permission to access the specified resource.

  aws:ec2:SecurityGroup (mySecurityGroup
):
    error:   sdk-v2/provider2.go:515: sdk.helper_schema: deleting ENIs using Security Group (sg-01b80436ca56f720f): 1 error occurred:
    	* detaching RDS ENI (eni-03127015e02db07dc): detaching EC2 Network Interface (eni-03127015e02db07dc/eni-attach-06572ed1f8f103c73): operation error EC2: DetachNetworkInterface, https response error StatusCode: 400, RequestID: 84bbf0cd-b697-4890-860a-a4a573851674, api error AuthFailure: You do not have permission to access the specified resource.
    
    : provider=aws@6.72.0

  pulumi:pulumi:Stack (aws-rds-module-dev-check-no-changes):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/guin/go/src/github.com/pulumi/pulumi-terraform-module-provider/bin/pulumi-resource-terraform-module
    error: update failed

Resources:
    - 1 deleted
```

Note that the resource tree is not showing the dependsOn relationship.

**Update:**
Attempted to see if https://github.com/pulumi/pulumi-terraform-module/pull/179 would address this. Still the same error.

Here's a gist of the statefile right after the first dailed delete attempt: https://gist.github.com/guineveresaenger/df85f34853ae29309083e5aa951d3548

https://gist.github.com/guineveresaenger/df85f34853ae29309083e5aa951d3548

### PR DESCRIPTION
**Pull request by t0yv0**
This change fixes dependency handling. The fix is coarse-grained but important for correctly ordering deletes. The implementation is currently lacking capabilities to track dependencies precisely through the TF black box.

What this does: 

- if dependencies are passed via dependsOn ResourceOption, Module ComponentResource now correctly depends on these

- if dependencies are passed implicitly with inputs, ModuleState Custom Resource now depends on all these dependencies. This means, in particular, that `tofu destroy` will now have to complete before the dependencies start getting destroyed themselves. This fixes issues such as #234 

- if Pulumi resources depend on any of the module's outputs, they now also will depend on ModuleState custom resource directly, and transitively on all the dependencies of the module's inputs. They should order their destroy operations accordingly. They also depend on the Component resource itself, respecting dependsOn option on that.

Fixes #151
Fixes #234

Questions:

- [x] Does the code need to process `ConstructRequest.{Dependencies, InputDependencies}` or it is obsoleted by first-class Output values? ==> Dependencies is now handled, InputDependencies are not needed because first-class outputs are accepted instead
- [x] Do we need to copy up the URN of ModuleState resource and add it to the broadcast of module outputs, so that resources that consume the outputs of the Component resource not only depend on the Component and indirectly on ModuleState because it is the child of the Component, but also directly depend on the ModuleState? ==> yes, done
- [ ] Do dependencies work through first-class providers? That might need further work around Configure; https://github.com/pulumi/pulumi-terraform-module/issues/187 is tracking

### CODE REVIEW

**Comment by t0yv0** [comment]
@justinvp somehow can't tag you as reviewer, strange GH features.

File: tests/examples_test.go [hunk 1]
```diff
@@ -41,20 +38,21 @@ func Test_RdsExample(t *testing.T) {
...
 		optpreview.ProgressStreams(os.Stdout),
 	)
 
-	// TODO [pulumi/pulumi-terraform-module#151] Property dependencies aren't flowing through
-	integrationTest.Destroy(t, optdestroy.TargetDependents(), optdestroy.Target([]string{
-		rdsUrn,
-	}))
+	integrationTest.Destroy(t)
+
+	// integrationTest.Destroy(t, optdestroy.TargetDependents(), optdestroy.Target([]string{
```
Comment (t0yv0) [inline tests/examples_test.go:53]: Waiting on CI to confirm this works as expected.

File: tests/acc_test.go [hunk 2]
```diff
@@ -1216,10 +1217,30 @@ func Test_Dependencies(t *testing.T) {
...
 			autogold.Expect(map[resource.PropertyKey][]urn.URN{
-				resource.PropertyKey("__module"):     {},
-				resource.PropertyKey("moduleInputs"): {},
+				resource.PropertyKey("__module"): {},
+				//nolint:lll
+				resource.PropertyKey("moduleInputs"): {urn.URN("urn:pulumi:test::ts-dep-tester::random:index/randomInteger:RandomInteger::seed")},
+			}).Equal(t, r.PropertyDependencies)
+		}
+
+		// TODO is this enough for dependent to depend on randmod:index:Module that itself does not seem to
```
Comment (t0yv0) [inline tests/acc_test.go:1229]: This feels a bit sketchy.. I am wondering if transitive deps actually do not work as yet.

File: pkg/property/unmarshal_test.go [hunk 3]
```diff
@@ -34,6 +35,9 @@ func TestUnmarhsalPropertiesThreadThroughRegisterResource(t *testing.T) {
 	type testCase struct {
 		name   string
 		inputs resource.PropertyMap
+
+		// Only needed if turnaround value is a normalized form of the original value.
```
Comment (guineveresaenger) [inline pkg/property/unmarshal_test.go:39]: Is "turnaround value" an official term? 
Under what conditions does normalization happen?

File: pkg/modprovider/server.go [hunk 4]
```diff
@@ -341,11 +351,21 @@ func (s *server) Construct(
...
-		// TODO[https://github.com/pulumi/pulumi-terraform-module/issues/151] support Outputs in Unmarshal
-		KeepOutputValues: false,
+		KeepUnknowns:     true,
+		KeepSecrets:      true,
+		KeepResources:    true,
+		KeepOutputValues: true,
+	})
+
+	// Cannot yet track dependencies precisely through opentofu interaction; instead collect them all up in a big
+	// bag and reattach this bag to every single output of the module. Not doing this will not make the engine
```
Comment (guineveresaenger) [inline pkg/modprovider/server.go:361]:
```suggestion
	// bag and reattach this bag to every single output of the module. Doing this will make the engine
```

**Review by guineveresaenger — COMMENTED** [review]
I've verified that this indeed fixes #234.

Do we have confidence that turning Unknowns and Secrets into OutputProperty is safe?

File: pkg/modprovider/server.go (hunk 4 above)
Comment (guineveresaenger) [reply pkg/modprovider/server.go]: 👍

File: pkg/property/unmarshal_test.go (hunk 3 above)
Comment (t0yv0) [reply pkg/property/unmarshal_test.go]: NO it's not. I've reworded this. See `unknown`, `secret` and `output-known` cases for the conditions where normalization happens currently.

**Comment by t0yv0** [comment]
> Do we have confidence that turning Unknowns and Secrets into OutputProperty is safe?


Those are semantically equivalent. Also, secretes + unknowns should be under test in this repo AFAIK, though maybe something somewhere is lacking in rigor.

**Review by guineveresaenger — APPROVED** [review]
Really appreciate the comments here, thank you for letting me nit pick them.

**Review by justinvp — APPROVED** [review]
LGTM. Seems worth merging as-is.

To answer some of your questions...

---

> Does the code need to process ConstructRequest.{Dependencies, PropertyDependencies} or it is obsoleted by first-class Output values?

Just a note that "PropertyDependencies" is actually called `inputDependencies` on `ConstructRequest`, which I assume is what you mean. Yes, it is obsoleted by first-class Output values. Since you're handling that now, you can ignore `ConstructRequest.InputDependencies`.

`Dependencies` represents the `ResourceOptions.DependsOn`. You will want to handle it. You have this code:

https://github.com/pulumi/pulumi-terraform-module/blob/ab31764aebe5b5b14270bb8d0e6db141a7ca354b/pkg/modprovider/server.go#L361-L365

The `ResourceOption` being passed into the callback (currently ignored) will have the `DependsOn` filled in for you based on the ConstructRequest.Dependencies, via https://github.com/pulumi/pulumi/blob/6bb0e44f1bb9119435d9ec02217f5ebba9c4b9f3/sdk/go/pulumi/provider.go#L117-L119

You're going to want to think about passing that ResourceOption to your `NewModuleComponentResource` inside `Construct`, so the actual component gets the resource options that the user specified. I think it's a matter of passing it as the last arg of `NewModuleComponentResource`.

---

>  if Pulumi resources depend on any of the module's outputs, they now also will depend on all the dependencies of the module's inputs

> Do we need to copy up the URN of ModuleState resource and add it to the broadcast of module outputs, so that resources that consume the outputs of the Component resource not only depend on the Component and indirectly on ModuleState because it is the child of the Component, but also directly depend on the ModuleState?

It may be sufficient to only have the module's outputs depend on ModuleState, if ModuleState depends on all the inputs. Then you might not have to propagate all the input dependencies to the module outputs.

**Comment by t0yv0** [comment]
Test non-deterministic re-orders the deps sigh. I'll fix up.

```
      	resource.PropertyKey("max"): {
        		urn.URN("urn:pulumi:test::ts-dep-tester::randmod:index:Module::myrandmod"),
        		urn.URN("urn:pulumi:test::ts-dep-tester::random:index/randomInteger:RandomInteger::seed"),
        		urn.URN("urn:pulumi:test::ts-dep-tester::randmod:index:Module::myrandmod"),
        	},
```
