### PR TITLE
non-nullable inputs should be marked as required

### LINKED ISSUE #335: Required module inputs are generated as optional in SDKs
### What happened?

In TF modules are required to have a `name` parameter. This is highlighted in the editor, so is part of the TF type for a module.

In Pulumi this produces a runtime error instead

```
error: 
    Error: Missing required argument
    
      on pulumi.tf.json line 6, in module.http80:
       6:     }
    
    The argument "vpc_id" is required, but no definition was found.
    error: 
    Error: Missing required argument
    
      on pulumi.tf.json line 6, in module.http80:
       6:     }
    
    The argument "name" is required, but no definition was found.

  pulumi:pulumi:Stack (aws_module_security_group-dev):
    error: http80:index:Module resource 'http80' has a problem: NewModuleComponentResource failed: Plan failed: error running plan: exit status 1
```

This seems like it should be part of the SDK instead and a type error there. Instead it is generated as an optional:

```
name: Input[str] | None = None,
```

### Example

```
pulumi new aws-python --yes
pulumi package add terraform-module terraform-aws-modules/security-group/aws//modules/http-80 http80
```

```python
import pulumi_aws as aws
import pulumi_http80 as http80

provider = aws.Provider("my-provider", region="us-east-1")
http80Provider = http80.Provider("provider", aws=provider.terraform_config().result)
http80.Module("http80")

```

### Output of `pulumi about`

```
CLI          
Version      3.171.0
Go Version   go1.24.3
Go Compiler  gc

Plugins
KIND      NAME              VERSION
resource  aws               6.81.0
language  python            3.171.0
resource  terraform-module  0.1.4
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #335

### CODE REVIEW

**Review by corymhall — APPROVED** [review]

**Comment by Zaid-Ajaj** [comment]
Looks like lots of inputs from modules we test are now flagging a ton of their inputs as non-nullable

File: pkg/modprovider/tfmodules.go [hunk 1]
```diff
@@ -365,7 +365,7 @@ func inferModuleSchema(
 			TypeSpec:    variableType,
 		}
 
-		if variable.Default.IsNull() && !variable.Nullable {
+		if variable.Default.IsNull() && !(variable.NullableSet && variable.Nullable) {
```
Comment (corymhall) [inline pkg/modprovider/tfmodules.go:368]: > Looks like lots of inputs from modules we test are now flagging a ton of their inputs as non-nullable

Do you know how the `Nullable` and `NullableSet` gets determined? This is one of the properties from the test failures that is being read as `required` now.

https://github.com/terraform-aws-modules/terraform-aws-s3-bucket/blob/0d781fbb515b1f64c46bfba04153bef091d50fc5/variables.tf#L133-L137

Comment (Zaid-Ajaj) [reply pkg/modprovider/tfmodules.go:368]: I believe `NullableSet` means that the source code has an attribute `nullable = <true | false>` and then `Nullable` if the `nullable` is set to true. I will look again 😅

**Comment by Zaid-Ajaj** [comment]
Auto-merged was enabled yesterday so this got merged as soon as the tests passed. 

cc @corymhall I fixed the issue using the following logic:
```go
nullable := variable.NullableSet && variable.Nullable
hasDefault := variable.Default.Type() != cty.NilType
optional := hasDefault || nullable
if !optional {
	inferredModuleSchema.RequiredInputs = append(inferredModuleSchema.RequiredInputs, key)
}
```
any default (null or otherwise) set will mean that the property is optional. Added a local test module to account for the different cases we have and the other tests passed without any changes
