### PR TITLE
Better missing credentials error when using AWS modules

### LINKED ISSUE #197: Unfortunate auth configuration error on AWS
It is unfortunate that we leak the underlying raw OpenTofu error message when you haven't configured your AWS credentials properly. This is probably going to be a common error message that people face. For example:

```
    error: vpc:index:Module resource 'my-vpc' has a problem: NewModuleComponentResource failed: Plan failed: error running plan: exit status 1

    Error: Invalid provider configuration

    Provider "registry.opentofu.org/hashicorp/aws" requires explicit
    configuration. Add a provider block to the root module and configure the
    provider's required arguments as described in the provider documentation.


    Error: No valid credential sources found

      with provider["registry.opentofu.org/hashicorp/aws"],
      on provider["registry.opentofu.org/hashicorp/aws"] with no configuration line 1:
      (source code not available)

    Please see https://registry.terraform.io/providers/hashicorp/aws
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found,
    operation error ec2imds: GetMetadata, exceeded maximum number of attempts, 3,
    request send failed, Get
    "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp
    169.254.169.254:80: connect: host is down
```

The most unfortunate part is that it differs from the equivalent (nicer) error message from Pulumi that users typically see:

```
  pulumi:providers:aws (default_6_71_0):
    error: pulumi:providers:aws resource 'default_6_71_0' has a problem: No valid credential sources found.
    Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/ for more information about providing credentials.
    NEW: You can use Pulumi ESC to set up dynamic credentials with AWS OIDC to ensure the correct and valid credentials are used.
    Learn more: https://www.pulumi.com/registry/packages/aws/installation-configuration/#dynamically-generate-credentials-via-pulumi-esc
```

Is it possible to somehow make this better? I naively assumed we'd configure all of the providers on the Pulumi side that get used by any of the TF modules you're using, and that this would have triggered the failure sooner than calling into the module.

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Resolves #197 

When using terraform AWS modules without credentials, we see an error that is terraform-specific and not actionable for Pulumi users. This missing credentials error is issued as an error log message. This PR intercepts logs to detect that error and return a nicer Pulumi-specific error similar to how we implemented it in pulumi-aws.

### CODE REVIEW

File: pkg/modprovider/logger.go [hunk 1]
```diff
@@ -121,6 +128,21 @@ func (l *resourceLogger) Log(ctx context.Context, level tfsandbox.LogLevel, mess
 		diagLevel = diag.Info
 	}
 
+	if diagLevel == diag.Error && isMissingCredentialsErrorFromAWS(message) {
+		// for AWS provider, we can detect missing credentials errors and provide a more helpful message
+		// that is specific to Pulumi users.
+		modifiedCredentialsError := []string{
+			"no valid credentials source found to configure the AWS provider.",
```
Comment (t0yv0) [inline pkg/modprovider/logger.go:135]: Perhaps reference https://github.com/pulumi/pulumi-terraform-module-provider/blob/a885a15185ec0fe9668f5a91a356eae8b2d69ac4/README.md?plain=1#L37 here or some such, as it's not super obvious specifically for the module providers how to do it, it is a little extra confusing.

Comment (t0yv0) [inline pkg/modprovider/logger.go:135]: If this could be in a text file for easy editing and then embed'ed in that'd be great!

**Review by t0yv0 — APPROVED** [review]

File: pkg/modprovider/logger.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/modprovider/logger.go]: Done ✅

Comment (Zaid-Ajaj) [reply pkg/modprovider/logger.go]: Added a link to the readme section ✅

**Comment by t0yv0** [comment]
🚢
