### PR TITLE
Simpler workdir cleanup

### LINKED ISSUE #166: AWS Lambda: Incorrect delete-replace on null_resource
I haven't sussed out what the generic problem is here, any insight would be appreciated.

The following program (taken from the e2e integration test) shows a Delete/Replace on the `null_resource` on Update after Create.

```typescript
const testlambda = new lambda.Module("test-lambda", {
    function_name: `guinstestlambda`,
    source_path: "/Users/guin/go/src/github.com/pulumi/module-experiments/aws-bucket/src/app.ts",
    runtime:  "nodejs22.x",
    handler: "app.handler",
})
```

Console output:

```
Resources:
    +-1 to replace
    8 unchanged

Do you want to perform this update? details
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::aws-bucket::pulumi:pulumi:Stack::aws-bucket-dev]
    ++lambda:tf:null_resource: (create-replacement)
        [id=module.test-lambda.null_resource.archive[0]]
        [urn=urn:pulumi:dev::aws-bucket::lambda:index:Module$lambda:tf:null_resource::module.test-lambda.null_resource.archive[0]]
        [provider=urn:pulumi:dev::aws-bucket::pulumi:providers:lambda::default_7_20_1::f525fb35-fe2e-4d8e-8ff7-554883eacd23]
      ~ id      : "9036867658327326146" => output<string>
      ~ triggers: {
          ~ timestamp: "1740784942832199000" => "1740786023492544000"
        }
    +-lambda:tf:null_resource: (replace)
        [id=module.test-lambda.null_resource.archive[0]]
        [urn=urn:pulumi:dev::aws-bucket::lambda:index:Module$lambda:tf:null_resource::module.test-lambda.null_resource.archive[0]]
        [provider=urn:pulumi:dev::aws-bucket::pulumi:providers:lambda::default_7_20_1::f525fb35-fe2e-4d8e-8ff7-554883eacd23]
      ~ id      : "9036867658327326146" => output<string>
      ~ triggers: {
          ~ timestamp: "1740784942832199000" => "1740786023492544000"
        }
    --lambda:tf:null_resource: (delete-replaced)
        [id=module.test-lambda.null_resource.archive[0]]
        [urn=urn:pulumi:dev::aws-bucket::lambda:index:Module$lambda:tf:null_resource::module.test-lambda.null_resource.archive[0]]
        [provider=urn:pulumi:dev::aws-bucket::pulumi:providers:lambda::default_7_20_1::f525fb35-fe2e-4d8e-8ff7-554883eacd23]
```

The same code run in Terraform does not show this diff so it's definitely a bug on our side.

The [module source code](https://github.com/terraform-aws-modules/terraform-aws-lambda/blob/84dfbfddf9483bc56afa0aff516177c03652f0c7/package.tf#L58) is building a zip archive and it looks like the filename is changing - due to a difference in build context perhaps? Are we doing odd things to the file system?

### PR DESCRIPTION
**Pull request by t0yv0**
Workspace files are retained across `pulumi up`  invocations, matching the expectation of modules such as the AWS Lambda Terraform Module to be able to persist information in the file system across invocations. 

Fixes #166 

As a side fix, DEBUG level logs no longer show through the product UI by default. This seems to have been an unintentional omission to send them at INFO level.

### CODE REVIEW

File: pkg/tfsandbox/workdir.go [hunk 1]
```diff
@@ -45,74 +47,59 @@ func ModuleWorkdir(source TFModuleSource, version TFModuleVersion) Workdir {
 // Get or create a folder under $TMPDIR matching the current Pulumi project and stack.
 //
 // If the folder exists, clean it up except for expensive assets (see [workdirClean]).
-func workdirGetOrCreate(workdir Workdir) (string, error) {
+func workdirGetOrCreate(ctx context.Context, logger Logger, workdir Workdir) (string, error) {
 	path := workdirPath(workdir)
 
 	if dirExists(path) {
+		logger.Log(ctx, Debug, fmt.Sprintf("Reusing working directory: %s", path))
```
Comment (t0yv0) [inline pkg/tfsandbox/workdir.go:54]: It is strange that I can observe Debug-level logs in the product. Hm..

**Comment by t0yv0** [comment]
The other problem is that everything becomes notice-ably slower. 

We are not ready for this change for some reason:

```
		// This project always rewrites the lockfile as it is stored in the Pulumi state. Avoid accidental
		// reuse from the cache. In case of creating from scratch this is moot and it will be recomputed.
		// filepath.Join(workdir, defaultLockFile),

```

In my understanding we were writing it all the time..  

Ah looks like locations such as

/var/folders/gd/3ncjb1lj5ljgk8xl5ssn_gvc0000gn/T/com.apple.shortcuts.mac-helper/pulumi-terraform-module/workdirs/by-module-source-and-version/terraform-aws-modules%2Flambda%2Faws/7.20.2/.terraform.l
ock.hcl

rely on this to be persisted as they are not rewriting it from the statefile. I will revert out.

File: pkg/modprovider/logger.go [hunk 2]
```diff
@@ -109,6 +109,8 @@ func (l *resourceLogger) Log(ctx context.Context, level tfsandbox.LogLevel, mess
 	var err error
 	var diagLevel diag.Severity
 	switch level {
+	case tfsandbox.Debug:
+		diagLevel = diag.Debug
```
Comment (corymhall) [inline pkg/modprovider/logger.go:113]: 👍🏻

File: tests/acc_test.go [hunk 3]
```diff
@@ -514,10 +514,9 @@ func TestE2eTs(t *testing.T) {
 			deleteExpect: map[string]int{
 				"delete": 9,
 			},
-			// TODO: [Fix delete-replace on null_resource](https://github.com/pulumi/pulumi-terraform-module/issues/166)
 			diffNoChangesExpect: map[apitype.OpType]int{
-				apitype.OpType("replace"): 1,
-				apitype.OpType("same"):    8,
+				apitype.OpType("update"): 1,
```
Comment (corymhall) [inline tests/acc_test.go:518]: Yay!

**Review by corymhall — APPROVED** [review]
