### PR TITLE
Apply required inputs when combining partial schema

### LINKED ISSUE #432: requiredInputs is not working to make iam fields required
### What happened?

I tried writing a config.json file to make the policy field required on the iam policy provider https://registry.terraform.io/modules/terraform-aws-modules/iam/aws/latest/submodules/iam-policy, https://github.com/pulumi/pulumi-terraform-module/blob/57e041c5d72d122e70052cdc74fa68d08f346e81/docs/config-reference.md

It didn't work, and the value was still marked as optional

### Example

const iamPolicy = new iampolicy.Module("mypolicy", {
  name: "elisabethpolicy",
  description: "this is a tester policy to allow viewing an s3 bucket",
});

config.json
{
  "requiredInputs": ["policy"]
}

command: pulumi package add terraform-module -- terraform-aws-modules/iam/aws//modules/iam-policy iampolicy --config config.json

### Output of `pulumi about`

CLI          
Version      3.177.0
Go Version   go1.24.4
Go Compiler  gc

Host     
OS       darwin
Version  15.3.1
Arch     arm64

Current Stack: team-ce/terraform-module-dogfooding/dev

Found no resources associated with team-ce/dev

Found no pending operations associated with team-ce/dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/ElisabethLich
User           ElisabethLich
Organizations  ElisabethLich, team-ce, demo
Token type     personal

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Fixes #432 combining required inputs from partial schema was not handled

### CODE REVIEW

File: pkg/modprovider/tfmodules.go [hunk 1]
```diff
@@ -518,6 +521,20 @@ func combineInferredModuleSchema(
 		}
 	}
 
+	// add required inputs to the inferred schema if they are not already present
+	for _, requiredInput := range partialInferredSchema.RequiredInputs {
+		alreadyExists := false
+		for _, existingRequiredInput := range inferredSchema.RequiredInputs {
```
Comment (corymhall) [inline pkg/modprovider/tfmodules.go:527]: nit: it might be worth it at this point to rename `InferredModuleSchema` to just `ModuleSchema` and then just use descriptive variable names to indicate where the schema is coming from (inferred, user provided, etc). Not being super familiar with this code I found it a little confusing because I don't think `partialInferredSchema` is actually "inferred" right?

Not something that needs to be addressed in this PR, just an observation (and feel free to disagree)

**Review by corymhall — APPROVED** [review]

File: pkg/modprovider/tfmodules.go (hunk 1 above)
Comment (Zaid-Ajaj) [reply pkg/modprovider/tfmodules.go:527]: No I agree with you, using `ModuleSchema` sounds better! I can refactor in a follow-up PR ✅
