### PR TITLE
Run init with `-upgrade` when module version is updated

### LINKED ISSUE #547: Errors after revisiting an infra package
### What happened?

I have some infrastructure I haven't updated in a few months - when trying to run `pulumi up`, I'm unable to because of a lockfile - is this something I can delete, and if so, where in my filesystem can I find this (or do I need to manually edit a state file)?

### Example

```
Error: Failed to resolve provider packages

Could not resolve provider hashicorp/aws: locked provider
registry.opentofu.org/hashicorp/aws 5.98.0 does not match configured version
constraint >= 6.0.0; must use tofu init -upgrade to allow selection of new
versions

```

### Output of `pulumi about`

CLI          
Version      3.197.0
Go Version   go1.25.1
Go Compiler  gc

Plugins
KIND      NAME    VERSION
language  nodejs  3.197.0

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by corymhall**
When a user upgrades a module, that module can require a newer version
of the underlying Terraform providers. When this happens you have to run
`tofu init -upgrade` in order to upgrade the version of the provider
that is used.

This PR updates the provider to save the module version to state so that
we can compare to the new version and `-update` if necessary.

fixes #547

### CODE REVIEW

File: pkg/modprovider/module.go [hunk 1]
```diff
@@ -269,15 +270,26 @@ func (h *moduleHandler) prepSandbox(
...
-	err = tf.Init(ctx, logger)
+	// If the module version changed between deployments, rerun init with -upgrade so the lockfile
+	// is refreshed to match the newer constraint set.
+	if needsInitUpgrade(oldOutputs, previousVersion, moduleVersion) {
+		logger.LogStatus(ctx, tfsandbox.Info, fmt.Sprintf(
+			"Module version changed from %s to %s; re-running init with -upgrade",
+			versionOrUnknown(previousVersion), versionOrUnknown(moduleVersion)))
+		err = tf.InitUpgrade(ctx, logger)
+	} else {
+		err = tf.Init(ctx, logger)
```
Comment (blampe) [inline pkg/modprovider/module.go:291]: Out of curiosity how does this differ from init?

**Review by blampe — APPROVED** [review]
