### PR TITLE
Fix inconsistent plan error

### LINKED ISSUE #198: Error: Provider produced inconsistent final plan
During an update, I triggered the below error:

```
     Type                         Name            Status              Info
     pulumi:pulumi:Stack          pulumiform-dev  **failed**          1 error
     └─ vpc:index:Module          my-vpc
 ~      └─ vpc:index:ModuleState  my-vpc-state    updated (0.27s)     [diff: ~moduleInputs]

Diagnostics:
  pulumi:pulumi:Stack (pulumiform-dev):
    error: vpc:index:Module resource 'my-vpc' has a problem: NewModuleComponentResource failed: Apply failed: error running tofu apply: exit status 1

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_public_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[0].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[1].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].outpost_arn: was null, but now
    cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].enable_lni_at_device_index: was
    null, but now cty.NumberIntVal(0).

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].ipv6_cidr_block: was null, but
    now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].customer_owned_ipv4_pool: was
    null, but now cty.StringVal("").

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: Provider produced inconsistent final plan

    When expanding the plan for
    terraform_data.internal_output_private_subnet_objects to include new values
    learned so far during apply, provider "terraform.io/builtin/terraform"
    produced an invalid new value for .input[2].map_customer_owned_ip_on_launch:
    was null, but now cty.False.

    This is a bug in the provider, which should be reported in the provider's own
    issue tracker.

    Error: creating EC2 Internet Gateway: attaching EC2 Internet Gateway (igw-0b9da2bfa472a4e0e) to VPC (vpc-0360a9757dd5387fb): operation error EC2: AttachInternetGateway, https response error StatusCode: 400, RequestID: 130de0a5-2887-4a09-8b99-63a9314d8d98, api error InvalidParameterValue: Network vpc-0360a9757dd5387fb already has an internet gateway attached

      with module.my-vpc.aws_internet_gateway.this[0],
      on .terraform/modules/my-vpc/main.tf line 1018, in resource "aws_internet_gateway" "this":
    1018: resource "aws_internet_gateway" "this" {


    Error: creating EC2 VPN Gateway: operation error EC2: CreateVpnGateway, https response error StatusCode: 400, RequestID: 0231a15d-b4e5-4351-80f1-ae8fee204af4, api error VpnGatewayLimitExceeded: The maximum number of virtual private gateways has been reached.

      with module.my-vpc.aws_vpn_gateway.this[0],
      on .terraform/modules/my-vpc/main.tf line 1155, in resource "aws_vpn_gateway" "this":
    1155: resource "aws_vpn_gateway" "this" {

Outputs:
  - privateSubnetIds: []
  - publicSubnetIds : []
  - vpcId           : "vpc-0360a9757dd5387fb"

Resources:
    ~ 1 updated
    2 unchanged

Duration: 33s
```

The program is:

```typescript
import * as aws from "@pulumi/aws";
import * as vpc from "@pulumi/vpc";

const myVpc = new vpc.Module("my-vpc", {
    cidr: "10.0.0.0/16",

    azs: aws.getAvailabilityZones().then(azs => azs.names.slice(0, 3)),
    private_subnets: ["10.0.1.0/24", "10.0.2.0/24", "10.0.3.0/24"],
    public_subnets: ["10.0.101.0/24", "10.0.102.0/24", "10.0.103.0/24"],

    enable_nat_gateway: true,
    enable_vpn_gateway: true,

    tags: {
        "Pulumi": "true",
        "Environment": "dev",
    },
});

export const vpcId = myVpc.vpc_id;
export const publicSubnetIds = myVpc.public_subnets;
export const privateSubnetIds = myVpc.private_subnets;
```

And here is the detailed diff of the update attempting to be performed:

```
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:dev::pulumiform::pulumi:pulumi:Stack::pulumiform-dev]
    + vpc:tf:aws_internet_gateway: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_internet_gateway::module.my-vpc.aws_internet_gateway.this[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn      : output<string>
        id       : output<string>
        owner_id : output<string>
        tags     : {
            Environment: "dev"
            Name       : ""
            Pulumi     : "true"
        }
        tags_all : output<string>
        vpc_id   : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_nat_gateway: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_nat_gateway::module.my-vpc.aws_nat_gateway.this[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id                     : output<string>
        association_id                    : output<string>
        connectivity_type                 : "public"
        id                                : output<string>
        network_interface_id              : output<string>
        private_ip                        : output<string>
        public_ip                         : output<string>
        secondary_private_ip_address_count: output<string>
        secondary_private_ip_addresses    : output<string>
        subnet_id                         : output<string>
        tags                              : {
            Environment: "dev"
            Name       : "-us-west-2c"
            Pulumi     : "true"
        }
        tags_all                          : {
            Environment: "dev"
            Name       : "-us-west-2c"
            Pulumi     : "true"
        }
    + vpc:tf:aws_route_table: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table::module.my-vpc.aws_route_table.public[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn             : output<string>
        id              : output<string>
        owner_id        : output<string>
        propagating_vgws: output<string>
        route           : output<string>
        tags            : {
            Environment: "dev"
            Name       : "-public"
            Pulumi     : "true"
        }
        tags_all        : {
            Environment: "dev"
            Name       : "-public"
            Pulumi     : "true"
        }
        vpc_id          : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.public[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_route_table: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table::module.my-vpc.aws_route_table.private[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn             : output<string>
        id              : output<string>
        owner_id        : output<string>
        propagating_vgws: output<string>
        route           : output<string>
        tags            : {
            Environment: "dev"
            Name       : "-private-us-west-2a"
            Pulumi     : "true"
        }
        tags_all        : {
            Environment: "dev"
            Name       : "-private-us-west-2a"
            Pulumi     : "true"
        }
        vpc_id          : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route::module.my-vpc.aws_route.private_nat_gateway[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        destination_cidr_block: "0.0.0.0/0"
        id                    : output<string>
        instance_id           : output<string>
        instance_owner_id     : output<string>
        nat_gateway_id        : output<string>
        network_interface_id  : output<string>
        origin                : output<string>
        route_table_id        : output<string>
        state                 : output<string>
        timeouts              : {
            create: "5m"
        }
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.public[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_route_table: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table::module.my-vpc.aws_route_table.private[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn             : output<string>
        id              : output<string>
        owner_id        : output<string>
        propagating_vgws: output<string>
        route           : output<string>
        tags            : {
            Environment: "dev"
            Name       : "-private-us-west-2b"
            Pulumi     : "true"
        }
        tags_all        : {
            Environment: "dev"
            Name       : "-private-us-west-2b"
            Pulumi     : "true"
        }
        vpc_id          : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.private[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2a"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.1.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-private-us-west-2a"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-private-us-west-2a"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route::module.my-vpc.aws_route.public_internet_gateway[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        destination_cidr_block: "0.0.0.0/0"
        gateway_id            : output<string>
        id                    : output<string>
        instance_id           : output<string>
        instance_owner_id     : output<string>
        network_interface_id  : output<string>
        origin                : output<string>
        route_table_id        : output<string>
        state                 : output<string>
        timeouts              : {
            create: "5m"
        }
    + vpc:tf:aws_route_table: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table::module.my-vpc.aws_route_table.private[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn             : output<string>
        id              : output<string>
        owner_id        : output<string>
        propagating_vgws: output<string>
        route           : output<string>
        tags            : {
            Environment: "dev"
            Name       : "-private-us-west-2c"
            Pulumi     : "true"
        }
        tags_all        : {
            Environment: "dev"
            Name       : "-private-us-west-2c"
            Pulumi     : "true"
        }
        vpc_id          : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_eip: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_eip::module.my-vpc.aws_eip.nat[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id       : output<string>
        arn                 : output<string>
        association_id      : output<string>
        carrier_ip          : output<string>
        customer_owned_ip   : output<string>
        domain              : "vpc"
        id                  : output<string>
        instance            : output<string>
        ipam_pool_id        : output<string>
        network_border_group: output<string>
        network_interface   : output<string>
        private_dns         : output<string>
        private_ip          : output<string>
        ptr_record          : output<string>
        public_dns          : output<string>
        public_ip           : output<string>
        public_ipv4_pool    : output<string>
        tags                : {
            Environment: "dev"
            Name       : "-us-west-2a"
            Pulumi     : "true"
        }
        tags_all            : {
            Environment: "dev"
            Name       : "-us-west-2a"
            Pulumi     : "true"
        }
        vpc                 : output<string>
    + vpc:tf:aws_eip: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_eip::module.my-vpc.aws_eip.nat[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id       : output<string>
        arn                 : output<string>
        association_id      : output<string>
        carrier_ip          : output<string>
        customer_owned_ip   : output<string>
        domain              : "vpc"
        id                  : output<string>
        instance            : output<string>
        ipam_pool_id        : output<string>
        network_border_group: output<string>
        network_interface   : output<string>
        private_dns         : output<string>
        private_ip          : output<string>
        ptr_record          : output<string>
        public_dns          : output<string>
        public_ip           : output<string>
        public_ipv4_pool    : output<string>
        tags                : {
            Environment: "dev"
            Name       : "-us-west-2b"
            Pulumi     : "true"
        }
        tags_all            : {
            Environment: "dev"
            Name       : "-us-west-2b"
            Pulumi     : "true"
        }
        vpc                 : output<string>
    + vpc:tf:aws_eip: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_eip::module.my-vpc.aws_eip.nat[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id       : output<string>
        arn                 : output<string>
        association_id      : output<string>
        carrier_ip          : output<string>
        customer_owned_ip   : output<string>
        domain              : "vpc"
        id                  : output<string>
        instance            : output<string>
        ipam_pool_id        : output<string>
        network_border_group: output<string>
        network_interface   : output<string>
        private_dns         : output<string>
        private_ip          : output<string>
        ptr_record          : output<string>
        public_dns          : output<string>
        public_ip           : output<string>
        public_ipv4_pool    : output<string>
        tags                : {
            Environment: "dev"
            Name       : "-us-west-2c"
            Pulumi     : "true"
        }
        tags_all            : {
            Environment: "dev"
            Name       : "-us-west-2c"
            Pulumi     : "true"
        }
        vpc                 : output<string>
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.public[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2b"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.102.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-public-us-west-2b"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-public-us-west-2b"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.public[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_vpn_gateway: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_vpn_gateway::module.my-vpc.aws_vpn_gateway.this[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        amazon_side_asn: "64512"
        arn            : output<string>
        id             : output<string>
        tags           : {
            Environment: "dev"
            Name       : ""
            Pulumi     : "true"
        }
        tags_all       : output<string>
        vpc_id         : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_nat_gateway: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_nat_gateway::module.my-vpc.aws_nat_gateway.this[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id                     : output<string>
        association_id                    : output<string>
        connectivity_type                 : "public"
        id                                : output<string>
        network_interface_id              : output<string>
        private_ip                        : output<string>
        public_ip                         : output<string>
        secondary_private_ip_address_count: output<string>
        secondary_private_ip_addresses    : output<string>
        subnet_id                         : output<string>
        tags                              : {
            Environment: "dev"
            Name       : "-us-west-2a"
            Pulumi     : "true"
        }
        tags_all                          : {
            Environment: "dev"
            Name       : "-us-west-2a"
            Pulumi     : "true"
        }
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.private[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2c"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.3.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-private-us-west-2c"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-private-us-west-2c"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route::module.my-vpc.aws_route.private_nat_gateway[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        destination_cidr_block: "0.0.0.0/0"
        id                    : output<string>
        instance_id           : output<string>
        instance_owner_id     : output<string>
        nat_gateway_id        : output<string>
        network_interface_id  : output<string>
        origin                : output<string>
        route_table_id        : output<string>
        state                 : output<string>
        timeouts              : {
            create: "5m"
        }
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.private[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.private[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2b"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.2.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-private-us-west-2b"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-private-us-west-2b"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.private[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.public[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2c"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.103.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-public-us-west-2c"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-public-us-west-2c"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
    + vpc:tf:aws_route_table_association: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route_table_association::module.my-vpc.aws_route_table_association.private[2]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        id            : output<string>
        route_table_id: output<string>
        subnet_id     : output<string>
    + vpc:tf:aws_route: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_route::module.my-vpc.aws_route.private_nat_gateway[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        destination_cidr_block: "0.0.0.0/0"
        id                    : output<string>
        instance_id           : output<string>
        instance_owner_id     : output<string>
        nat_gateway_id        : output<string>
        network_interface_id  : output<string>
        origin                : output<string>
        route_table_id        : output<string>
        state                 : output<string>
        timeouts              : {
            create: "5m"
        }
    + vpc:tf:aws_nat_gateway: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_nat_gateway::module.my-vpc.aws_nat_gateway.this[1]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        allocation_id                     : output<string>
        association_id                    : output<string>
        connectivity_type                 : "public"
        id                                : output<string>
        network_interface_id              : output<string>
        private_ip                        : output<string>
        public_ip                         : output<string>
        secondary_private_ip_address_count: output<string>
        secondary_private_ip_addresses    : output<string>
        subnet_id                         : output<string>
        tags                              : {
            Environment: "dev"
            Name       : "-us-west-2b"
            Pulumi     : "true"
        }
        tags_all                          : {
            Environment: "dev"
            Name       : "-us-west-2b"
            Pulumi     : "true"
        }
    + vpc:tf:aws_subnet: (create)
        [urn=urn:pulumi:dev::pulumiform::vpc:index:Module$vpc:tf:aws_subnet::module.my-vpc.aws_subnet.public[0]]
        [provider=urn:pulumi:dev::pulumiform::pulumi:providers:vpc::default_5_18_1::6b687221-58b0-469a-b856-d789e12cf0eb]
        arn                                           : output<string>
        assign_ipv6_address_on_creation               : false
        availability_zone                             : "us-west-2a"
        availability_zone_id                          : output<string>
        cidr_block                                    : "10.0.101.0/24"
        enable_dns64                                  : false
        enable_resource_name_dns_a_record_on_launch   : false
        enable_resource_name_dns_aaaa_record_on_launch: false
        id                                            : output<string>
        ipv6_cidr_block_association_id                : output<string>
        ipv6_native                                   : false
        map_public_ip_on_launch                       : false
        owner_id                                      : output<string>
        private_dns_hostname_type_on_launch           : output<string>
        tags                                          : {
            Environment: "dev"
            Name       : "-public-us-west-2a"
            Pulumi     : "true"
        }
        tags_all                                      : {
            Environment: "dev"
            Name       : "-public-us-west-2a"
            Pulumi     : "true"
        }
        vpc_id                                        : "vpc-0360a9757dd5387fb"
```

Attached is the stack state export JSON.

[inconsistentFinalPlanStackState.json](https://github.com/user-attachments/files/19145093/inconsistentFinalPlanStackState.json)

### PR DESCRIPTION
**Pull request by corymhall**
This is a fix for the inconsistent plan error.

### Background

To expose outputs from a module, we need to account for the secretness of the outputs
If you try and output a secret value without setting `sensitive: true` in the output
The deployment will fail. We also need to be able to handle this dynamically since we won't know
the secret status until after the operation, and we need to write the output definition when we create the file (before the operation).

### Previous Solution

In #132 we added support for module outputs by using a `terraform_data` resource as a proxy for the output. This allowed us to account for the dynamic nature of the secret since we could determine the secret status of the value using the same method that we use for all other resource properties.

This ran into an issue #198 where `terraform_data` resources cannot be used if the value may be "inconsistent". A very common case that is used in most modules is to define an output like this:

```hcl
output "default_security_group_id" {
  description = "The ID of the security group created by default on VPC creation"
  value       = try(aws_vpc.this[0].default_security_group_id, null)
}
```

`try` is used because most modules will conditionally create resources and need to handle the case where the resource was not created and the value doesn't exist. This is a common case, but there may be other cases of this "inconsistent" data.

### New Solution

This PR tries a new solution of using output values with a combination of the [nonsensitive](https://developer.hashicorp.com/terraform/language/functions/nonsensitive) and [issensitive](https://developer.hashicorp.com/terraform/language/functions/issensitive) functions. We can use the `issensitive` function to dynamically determine whether the value is sensitive or not. Unfortunately it is not possible to use functions in the `output.sensitive` field (e.g. `sensitive: "${issensitive(module.source_module.output_name1)}"` won't work).

To work around this we use two outputs for each output value:
- The first output is the actual value that we mark as non-sensitive to avoid the error
- The second output is a boolean that indicates whether the value is a secret or not.

```json
"output": {
  "name1": {
      "value": "${nonsensitive(module.source_module.output_name1)}"
  },
  "internal_output_is_secret_name1": {
      "value": "${issensitive(module.source_module.output_name1)}"
  },
  ...
}
```

fixes #198

### CODE REVIEW

**Comment by corymhall** [comment]
This change is part of the following stack:

- #218 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>

**Comment by t0yv0** [comment]
Can you reference what `try` does?  Ah https://developer.hashicorp.com/terraform/language/functions/try

So in case of an error this will swallow data which is not great.

We need some creative thinking here actually, and this got me thinking about other functions we can use:

https://developer.hashicorp.com/terraform/language/functions/nonsensitive
https://developer.hashicorp.com/terraform/language/functions/issensitive

These look intriguing. What if we abandoned wrapping module outputs in terraform_data but instead directly exported them as we did before the workaround from the top-level module, but this time instead of propagating the module M's output o we would propagate `nonsensitive(o)` and a separate boolean for `issensitive(o)` to reconstruct this on Pulumi side?

Will this work? ONe interesting case if sensitive bits are not at the top-level of `o`.

**Comment by corymhall** [comment]
> These look intriguing. What if we abandoned wrapping module outputs in terraform_data but instead directly exported them as we did before the workaround from the top-level module, but this time instead of propagating the module M's output o we would propagate nonsensitive(o) and a separate boolean for issensitive(o) to reconstruct this on Pulumi side?

This is interesting, let me give it a shot.

**Comment by t0yv0** [comment]
This is great! Can we pin it with a simple test? 

Also with regard to testing I was curious if `nonsensitive()` and `issensitive()` take care of nested secrets or that's something left for later.

Apparently it is not recursive so we have this:
https://github.com/hashicorp/terraform/issues/32868

Example:

```terraform
module "m" {
  source = "./m"
  inputvar = sensitive(10)
}

output "exposed" {
  value = nonsensitive(module.m.outputvar)
}
```

With this module:

inputs.tf:

```terraform
variable "inputvar" {
  type    = number
  default = 16
}
```

infra.tf:

```terraform
resource "random_string" "random" {
  length           = 16
  special          = true
  override_special = "/@£$"
}
```

outputs.tf:

```terraform
output "outputvar" {
  value = {
    "X" = var.inputvar,
    "A" = "B"
  }
}
```

I get the dreaded:

```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: Output refers to sensitive values
│ 
│   on infra.tf line 6:
│    6: output "exposed" {
│ 
│ To reduce the risk of accidentally exporting sensitive data that was intended to be only internal, Terraform requires that any root module output containing sensitive data be explicitly marked as sensitive, to confirm your
│ intent.
│ 
│ If you do intend to export this data, annotate the output value as sensitive by adding the following argument:
│     sensitive = true
╵
```

**Comment by t0yv0** [comment]
I've tried this but similarly issensitive is non-recursive so it does not detect the presence of nested secrets 🤔 

```terraform
module "webservers" {
  source   = "./webservers"
  inputvar = sensitive(10)
}

output "exposed" {
  value     = module.webservers.outputvar
  sensitive = true
}

output "exposed_is_sensitive" {
  value = issensitive(module.webservers.outputvar)
}

```

**Review by t0yv0 — APPROVED** [review]
Interesting, seems to work!

One limitation I think we still have is secret floating, if any of the innards of an output are secret, the entire thing is secret. That is acceptable for starters, we can document this.

File: pkg/tfsandbox/tf_file.go [hunk 1]
```diff
@@ -213,11 +213,12 @@ func CreateTFFile(
...
-		mOutputs[output.Name] = map[string]interface{}{
-			"value": fmt.Sprintf("${nonsensitive(module.%s.%s)}", name, output.Name),
+		mOutputs[output.Name] = map[string]any{
+			// wrapping in jsondecode/jsonencode to workaround an issue where nonsensitive/issensitive is not recursive
+			"value": fmt.Sprintf("${jsondecode(nonsensitive(jsonencode(module.%s.%s)))}", name, output.Name),
 		}
-		mOutputs[fmt.Sprintf("%s%s", terraformIsSecretOutputPrefix, output.Name)] = map[string]interface{}{
-			"value": fmt.Sprintf("${issensitive(module.%s.%s)}", name, output.Name),
+		mOutputs[fmt.Sprintf("%s%s", terraformIsSecretOutputPrefix, output.Name)] = map[string]any{
+			"value": fmt.Sprintf("${jsondecode(issensitive(jsonencode(module.%s.%s)))}", name, output.Name),
```
Comment (t0yv0) [inline pkg/tfsandbox/tf_file.go:221]: Should this just be :

```
issensitive(jsonencode(module.%s.%s))
```

Do we need outer jsondecode? issensitive returns bool right?
