### PR TITLE
Handle partial failures in tofu apply

### LINKED ISSUE #183: Partial failure: when TF provisions some resources but not all
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

It is possible for an operation such as `tofu apply` to provision some resources but fail to provision others. We need to test for this case and make sure that the partial failure is reflected sensibly to Pulumi.

- [X] Apply #249
- [ ] Refresh
- [ ] Delete #254

### PR DESCRIPTION
**Pull request by corymhall**
This PR handles the case where `tofu apply` fails, but some resources
have been provisioned. As long as we can read the TF state file we will
continue to process the child resources and only after they have been
processed will we fail the component.

This is what a partial deployment will look like now (based on the
example test added).

```console
Previewing update (chall)

View in Browser (Ctrl+O): https://app.pulumi.com/chall-pulumi-corp/partial-apply/chall/previews/b0d1e4be-9ef0-4f84-9211-a241baed39fa

     Type                                              Name                                                      Plan       Info
 +   pulumi:pulumi:Stack                               partial-apply-chall                                       create     2 warnings
 +   └─ localmod:index:Module                          test-localmod                                             create
 +      ├─ localmod:index:ModuleState                  test-localmod-state                                       create
 +      ├─ localmod:tf:aws_iam_role_policy_attachment  module.test-localmod.aws_iam_role_policy_attachment.this  create
 +      └─ localmod:tf:aws_iam_role                    module.test-localmod.aws_iam_role.this                    create

Diagnostics:
  pulumi:pulumi:Stack (partial-apply-chall):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module

Outputs:
    roleArn: output<string>

Resources:
    + 5 to create

Do you want to perform this update? yes
Updating (chall)

View in Browser (Ctrl+O): https://app.pulumi.com/chall-pulumi-corp/partial-apply/chall/updates/8

     Type                              Name                                    Status                  Info
 +   pulumi:pulumi:Stack               partial-apply-chall                     **creating failed**     1 error; 2 warnings
 +   └─ localmod:index:Module          test-localmod                           **creating failed**     1 error
 +      ├─ localmod:index:ModuleState  test-localmod-state                     created (6s)
 +      └─ localmod:tf:aws_iam_role    module.test-localmod.aws_iam_role.this  created (0.52s)

Diagnostics:
  localmod:index:Module (test-localmod):
    error:
    Error: attaching IAM Policy (arn:aws:iam::aws:policy/ReadOnlyAccessFAIL) to IAM Role (chall20250325181048301400000001): operation error IAM: AttachRolePolicy, https response error StatusCode: 404, RequestID: eb96a2d4-87bc-48d0-9708-b62cf8a69f7f, NoSuchEntity: Policy arn:aws:iam::aws:policy/ReadOnlyAccessFAIL does not exist or is not attachable.

      with module.test-localmod.aws_iam_role_policy_attachment.this,
      on .terraform/modules/test-localmod/main.tf line 31, in resource "aws_iam_role_policy_attachment" "this":
      31: resource "aws_iam_role_policy_attachment" "this" {

  pulumi:pulumi:Stack (partial-apply-chall):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module
    error: localmod:index:Module resource 'test-localmod' has a problem: NewModuleComponentResource failed: Apply failed: exit status 1

Resources:
    + 4 created

Duration: 11s

❯ pulumi up
aws-vault exec dev-admin -- pulumi up
Previewing update (chall)

View in Browser (Ctrl+O): https://app.pulumi.com/chall-pulumi-corp/partial-apply/chall/previews/2ba3b950-11c3-408e-864f-8dc31103ba2b

     Type                                              Name                                                      Plan       Info
     pulumi:pulumi:Stack                               partial-apply-chall                                                  2 warnings
     └─ localmod:index:Module                          test-localmod
 +      └─ localmod:tf:aws_iam_role_policy_attachment  module.test-localmod.aws_iam_role_policy_attachment.this  create

Diagnostics:
  pulumi:pulumi:Stack (partial-apply-chall):
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module
    warning: using pulumi-resource-terraform-module from $PATH at /Users/chall/work/pulumi-terraform-module/partial-deploy/bin/pulumi-resource-terraform-module

Outputs:
  + roleArn: "arn:aws:iam::616138583583:role/chall20250325181048301400000001"

Resources:
    + 1 to create
    4 unchanged
```

## Notes

- We show the error on the module component resource and the user never
  sees the resource that fails. If we were to ever solve #247 we might
  be able to also attach the error to the correct child resource

## Questions

- [ ] Are there cases where Terraform will fail to create a resource and
  save a partial state? I'm not sure how the next up is handled, would
  it be an update or a create?

fixes #183

### CODE REVIEW

File: pkg/tfsandbox/apply.go [hunk 1]
```diff
@@ -10,24 +10,24 @@ import (
...
 
 // Apply runs the terraform apply command and returns the final state
 func (t *Tofu) apply(ctx context.Context, logger Logger) (*tfjson.State, error) {
 	logWriter := newJSONLogPipe(ctx, logger)
 	defer logWriter.Close()
 
-	if err := t.tf.ApplyJSON(ctx, logWriter); err != nil {
-		return nil, fmt.Errorf("error running tofu apply: %w", err)
+	applyErr := t.tf.ApplyJSON(ctx, logWriter)
+	// if the apply failed just log it to debug logs and continue
```
Comment (t0yv0) [inline pkg/tfsandbox/apply.go:27]: Style nit: may be good to lift to `func (t *Tofu) Apply(ctx context.Context, logger Logger) (*State, error) {` docstring as that's part of the contract.. This can now return non-nil errors together with non-nil State. That's a tad weird so worth documenting at the boundary.

File: pkg/modprovider/module_component.go [hunk 2]
```diff
@@ -206,10 +211,7 @@ func newModuleComponentResource(
 		moduleOutputs = plan.Outputs()
 	} else {
 		// DryRun() = false corresponds to running pulumi up
-		tfState, err := tf.Apply(ctx.Context(), logger)
-		if err != nil {
-			return nil, nil, nil, fmt.Errorf("Apply failed: %w", err)
-		}
+		tfState, applyErr = tf.Apply(ctx.Context(), logger)
```
Comment (t0yv0) [inline pkg/modprovider/module_component.go:214]: Thinking through control flow here, this is really a little concerning, can all the code after this code really handle the partial state? First of all, technically we're sure tfState is never nil or such right?

Something I can think of:

```
moduleOutputs = tfState.Outputs()
```

What if the tfState is a partially failed state, in such a way that resources that did not work were necessary for computing the outputs. Does Pulumi work in this case? Does it still produce the outputs? If so with what values?

Comment (t0yv0) [reply pkg/modprovider/module_component.go:214]: I guess you could flag that so tfState.Outputs() does not run unnecessarily.

**Comment by t0yv0** [comment]
Regarding your question, I filed https://github.com/pulumi/pulumi-terraform-module/issues/251

Seems sufficiently rare so can backlog for now until upvotes come in.

File: tests/acc_test.go [hunk 3]
```diff
@@ -176,6 +176,47 @@ func TestLambdaMemorySizeDiff(t *testing.T) {
...
+	// Set prefix via config
+	integrationTest.SetConfig(t, "prefix", prefix)
+
+	// Generate package
+	pulumiPackageAdd(t, integrationTest, localProviderBinPath, localMod, "localmod")
+	_, err = integrationTest.CurrentStack().Up(integrationTest.Context(), optup.Diff(),
+		optup.ErrorProgressStreams(os.Stderr),
+		optup.ProgressStreams(os.Stdout),
+	)
+	assert.Errorf(t, err, "expected error on up")
```
Comment (t0yv0) [inline tests/acc_test.go:203]: Can we check the state file to see if the resource records for child resources that did succeed got written out?

Can we also see what the module output values are?

**Comment by t0yv0** [comment]
This is rather elegant I love it we should probably start with this. On a call we discussed another possibility for displaying errors a little more precisely. Looks like Module resource needs to fail like in the PR, and ModuleState resource needs to commit - that's all good. But if an error pertains to a child resource, we could emit a RegisterResource for that resource and then surface the error from a CRUD handler of that resource. That way it might look more natural. Module still needs to fail though as discussed. WDYT? Worth backlogging?

**Comment by t0yv0** [comment]
We also still have the possibility of partially failing Delete/destroy and partially failing Refresh if I am not mistaken. Refresh is an alias for apply. Backlog those perhaps for now?

File: pkg/modprovider/module_component.go (hunk 2 above)
Comment (corymhall) [reply pkg/modprovider/module_component.go:214]: > can all the code after this code really handle the partial state?

Yes it should be able to. Maybe partial state is the wrong term to use here. It's the complete state, just with some resources not applied yet. Our processing here will match how Terraform sees the current state. If some resources were not applied then they won't be in the state and we won't process them. If Terraform failed to create a resource, but wrote some state for that resource (maybe it's missing some outputs), then we will also create a child resource that matches how Terraform current sees that resource. On the next apply Terraform will do something with that resource (update, replace, etc) and we will process that operation.

> First of all, technically we're sure tfState is never nil or such right?

Yes the `tfexec.Show` throws an error if the state is nil. 

> moduleOutputs = tfState.Outputs()

If apply fails and we have a partial state that we are processing, we will just process any outputs that are available. We don't look for specific outputs, we just process what's there.

> I guess you could put it under if-then-else so tfState.Outputs() does not run unnecessarily.

Yes we can do that for performance reasons since we never do anything with those outputs if the apply failed.

Comment (t0yv0) [reply pkg/modprovider/module_component.go:214]: > we just process what's there.

Ok so that sounds like there's no special "failed" markers in those outputs that depend on failed resources, nothing in the code to panic. That's good. My concern here is not perf but errors.

File: pkg/modprovider/module_component.go [hunk 4]
```diff
@@ -257,6 +259,10 @@ func newModuleComponentResource(
 		cr.Await(ctx.Context())
 	}
 
+	if applyErr != nil {
+		return nil, nil, nil, fmt.Errorf("Apply failed: %w", applyErr)
```
[the remark this answers is not in the document]
Comment (t0yv0) [reply pkg/modprovider/module_component.go:263]: I think you are right. The module failure is total, not like some outputs failed and some didn't. Thanks for talking through this with me.

**Review by t0yv0 — APPROVED** [review]
